routes:
  /categorias/:
    template: categorias
  /autores/:
    template: autores

collections:
  /:
    permalink: /{slug}/
    filter: tag:-hash-agenda
    template:
      - index
  /featured/:
    permalink: /featured/{slug}/
    filter: featured:true
    template:
      - index
  /agenda/:
    permalink: /agenda/{slug}/
    filter: tag:hash-agenda
    template:
      - agenda

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
